// <auto-generated />
using System;
using ItamBackend.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ItamBackend.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407024209_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ItamBackend.Api.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpleado"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cargo");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departamento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_completo");

                    b.HasKey("IdEmpleado");

                    b.ToTable("empleados");
                });

            modelBuilder.Entity("ItamBackend.Api.Models.Equipo", b =>
                {
                    b.Property<int>("IdEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_equipo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEquipo"));

                    b.Property<string>("CodigoItam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_itam");

                    b.Property<string>("EstadoEquipo")
                        .HasColumnType("text")
                        .HasColumnName("estado_equipo");

                    b.Property<int?>("IdEmpleadoAsignado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado_asignado");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modelo");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_serie");

                    b.Property<string>("TipoEquipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_equipo");

                    b.HasKey("IdEquipo");

                    b.HasIndex("IdEmpleadoAsignado");

                    b.ToTable("equipos");
                });

            modelBuilder.Entity("ItamBackend.Api.Models.Equipo", b =>
                {
                    b.HasOne("ItamBackend.Api.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleadoAsignado");

                    b.Navigation("Empleado");
                });
#pragma warning restore 612, 618
        }
    }
}
