version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: itam_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: itam_keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/${DB_NAME}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KC_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_URL}
      KC_HTTP_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm.json
    command: start-dev --import-realm 
    depends_on:
      - db
    restart: unless-stopped

  backend:
    build:
      context: ./ItamBackend.Api
      dockerfile: Dockerfile
    container_name: itam_backend
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - Jwt__Authority=${KEYCLOAK_URL}/realms/itam-realm
    ports:
      - "8000:8080"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./itam-frontend
      dockerfile: Dockerfile
    container_name: itam_frontend
    environment:
      - API_URL=${BACKEND_URL}
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata: