
server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # 🔥 LA MAGIA: Si no encuentra el archivo, redirige a index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
